name: super_green_app
description: SuperGreenLab&#x27;s mobile app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.4+41

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  heic_to_jpg:
  enum_to_string:
  uni_links:
  tuple:
  share_extend:
  fluttertoast:
  flutter_email_sender:
  visibility_detector:
  devicelocale:
  yaml:
  camera:
  multicast_dns:
  http:
  rxdart:
  flutter_svg:
  permission_handler: 4.4.0+hotfix.2
  moor:
  moor_ffi: 0.5.0
  path_provider:
  path:
  hive:
  hive_flutter:
  bloc:
  flutter_bloc:
  provider:
  equatable:
  url_launcher:
  basic_utils:
  flutter_speed_dial:
    path: ./vendor/flutter_speed_dial
  event_bus:
  video_player:
  keyboard_visibility:
  video_thumbnail:
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  intl:
  intl_translation:
  flutter_swiper:
  charts_flutter:
  flutter_markdown:
  flutter_ble_lib:
  youtube_player_flutter:
  matrix_gesture_detector:
    path: ./vendor/matrix_gesture_detector
  connectivity:
  flutter_local_notifications:
  exif:
  media_picker_builder:
    # path: ../media_picker_builder/ 
    git: https://github.com/supergreenlab/media_picker_builder.git
  image:
  device_info:
  wifi_iot:
    git: https://github.com/alternadom/WiFiFlutter.git
  flutter:
    sdk: flutter
  cupertino_icons:

dependency_overrides:
  analyzer: 0.39.14
  moor_ffi:
    git:
      url: https://github.com/simolus3/moor.git
      ref: develop
      path: moor_ffi
#  path: 1.7.0

dev_dependencies:
  hive_generator:
  moor_generator:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/feed_form/
    - assets/plant_infos/
    - assets/feed_card/
    - assets/box_setup/
    - assets/home/
    - assets/settings/
    - assets/products/
    - assets/products/bundle/
    - assets/products/growbox/
    - assets/products/growing_medium/
    - assets/products/nutrients/
    - assets/products/seeds/
    - assets/products/toolbox/
